version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run  --omit=tests/test_*.py -m unittest discover tests

      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coverage html -d test-reports/coverage.html

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel
            cp dist/*.whl test-reports

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            sphinx-build -M html doc test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports